version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    assignees:
      - "abartrim"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      python-version-updates:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:15"
      timezone: "UTC"
    assignees:
      - "abartrim"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      npm-version-updates:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "UTC"
    assignees:
      - "abartrim"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      docker-version-updates:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:45"
      timezone: "UTC"
    assignees:
      - "abartrim"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      github-actions-version-updates:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"