/*
 * rrweb-style replay integration example for SOBS RUM.
 *
 * This example demonstrates the payload contract only.
 * It assumes your app uploads replay payloads to your own backend/storage
 * and receives replay metadata ({ id, url }).
 */

(function (global) {
  'use strict';

  // Placeholder API. Replace with your own upload endpoint.
  async function uploadReplaySnapshot(events) {
    const response = await fetch('/api/replay/upload', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ provider: 'rrweb', events })
    });
    if (!response.ok) throw new Error('Replay upload failed');
    return response.json(); // expected: { id: 'replay-123', url: 'https://.../replay-123' }
  }

  async function attachReplayContextAndCapture(error) {
    // In a real rrweb integration, this would be recent rrweb event data.
    const replayEvents = [{ type: 'meta', ts: Date.now() }];
    const replayRef = await uploadReplaySnapshot(replayEvents);

    // Attach replay metadata to the next captured browser error.
    global.SOBS.setReplayContext(
      {
        id: replayRef.id,
        url: replayRef.url,
        provider: 'rrweb'
      },
      {
        ttlMs: 15000,
        consumeOnce: true
      }
    );

    // Optional screenshot artifact metadata if generated by your app.
    global.SOBS.setArtifactContext(
      {
        type: 'screenshot',
        id: 'shot-' + Date.now(),
        url: 'https://example.com/artifacts/shot-' + Date.now() + '.png'
      },
      { ttlMs: 15000, consumeOnce: true }
    );

    global.SOBS.captureException(error, {
      errorSource: 'captureException',
      message: error && error.message ? error.message : 'Unhandled UI failure'
    });
  }

  // Demo trigger.
  global.addEventListener('click', async function onDemoClick(evt) {
    const target = evt.target;
    if (!target || target.id !== 'simulate-checkout-error') return;
    try {
      throw new Error('Checkout confirmation failed');
    } catch (error) {
      try {
        await attachReplayContextAndCapture(error);
      } catch (uploadErr) {
        // Fall back to normal error capture when replay upload is unavailable.
        global.SOBS.captureException(uploadErr, { errorSource: 'replay-upload' });
      }
    }
  });
})(window);
